export const languageCodes = ["en", "hi", "bn", "or", "te", "pa", "ta"] as const;
export type Language = typeof languageCodes[number];
export const languages = [
  {code:"en", name:"English", native:"English", locale:"en-IN"},
  {code:"hi", name:"Hindi", native:"हिन्दी", locale:"hi-IN"},
  {code:"bn", name:"Bengali", native:"বাংলা", locale:"bn-IN"},
  {code:"or", name:"Odia", native:"ଓଡ଼ିଆ", locale:"or-IN"},
  {code:"te", name:"Telugu", native:"తెలుగు", locale:"te-IN"},
  {code:"pa", name:"Punjabi", native:"ਪੰਜਾਬੀ", locale:"pa-IN"},
  {code:"ta", name:"Tamil", native:"தமிழ்", locale:"ta-IN"}
] as const;
export const languageInfo = (code:string) => languages.find(l=>l.code===code) || languages[0];
export const isLanguage = (code:unknown):code is Language => languageCodes.includes(code as Language);
const en = {language:"Language",menu:"Menu",close:"Close",signin:"Sign in",register:"Create account",email:"Email address",password:"CareBodha password",name:"Full name",overview:"Overview",plan:"My care plan",teachback:"Teach-back",appointments:"Follow-up visits",family:"Family assistance",questions:"Clarification requests",notifications:"Notifications",settings:"Language & access",open:"Open CareBodha",how:"How it works",welcome:"Welcome to CareBodha",hero:"UNDERSTAND YOUR CARE",clarity:"with clarity.",description:"Your doctor’s instructions, explained in your language. Share what you understood and get help with the parts that need clarification."};
export type TextKey = keyof typeof en;
export const uiText:Record<Language,Record<TextKey,string>> = {
 en,
 hi:{language:"भाषा",menu:"मेनू",close:"बंद करें",signin:"साइन इन",register:"खाता बनाएँ",email:"ईमेल पता",password:"CareBodha पासवर्ड",name:"पूरा नाम",overview:"अवलोकन",plan:"मेरी देखभाल योजना",teachback:"अपने शब्दों में बताएँ",appointments:"अगली मुलाकात",family:"परिवार की सहायता",questions:"स्पष्टीकरण अनुरोध",notifications:"सूचनाएँ",settings:"भाषा और पहुँच",open:"CareBodha खोलें",how:"यह कैसे काम करता है",welcome:"CareBodha में स्वागत है",hero:"अपनी देखभाल समझें",clarity:"स्पष्टता के साथ।",description:"आपके डॉक्टर के निर्देश, आपकी भाषा में समझाए गए। आपने क्या समझा, बताएँ और जहाँ स्पष्टता चाहिए वहाँ सहायता पाएँ।"},
 bn:{language:"ভাষা",menu:"মেনু",close:"বন্ধ করুন",signin:"সাইন ইন",register:"অ্যাকাউন্ট তৈরি করুন",email:"ইমেইল ঠিকানা",password:"CareBodha পাসওয়ার্ড",name:"পুরো নাম",overview:"সারসংক্ষেপ",plan:"আমার পরিচর্যা পরিকল্পনা",teachback:"নিজের ভাষায় বলুন",appointments:"পরবর্তী সাক্ষাৎ",family:"পরিবারের সহায়তা",questions:"ব্যাখ্যার অনুরোধ",notifications:"বিজ্ঞপ্তি",settings:"ভাষা ও প্রবেশাধিকার",open:"CareBodha খুলুন",how:"কীভাবে কাজ করে",welcome:"CareBodha-তে স্বাগতম",hero:"আপনার পরিচর্যা বুঝুন",clarity:"স্পষ্টতার সঙ্গে।",description:"আপনার চিকিৎসকের নির্দেশ আপনার ভাষায় বোঝানো হয়। কী বুঝেছেন তা বলুন এবং অস্পষ্ট অংশে সাহায্য পান।"},
 or:{language:"ଭାଷା",menu:"ମେନୁ",close:"ବନ୍ଦ କରନ୍ତୁ",signin:"ସାଇନ୍ ଇନ୍",register:"ଖାତା ଖୋଲନ୍ତୁ",email:"ଇମେଲ୍ ଠିକଣା",password:"CareBodha ପାସୱାର୍ଡ",name:"ପୂରା ନାମ",overview:"ସାରାଂଶ",plan:"ମୋ ଯତ୍ନ ଯୋଜନା",teachback:"ନିଜ ଭାଷାରେ କୁହନ୍ତୁ",appointments:"ପରବର୍ତ୍ତୀ ସାକ୍ଷାତ",family:"ପରିବାରର ସହାୟତା",questions:"ସ୍ପଷ୍ଟୀକରଣ ଅନୁରୋଧ",notifications:"ସୂଚନା",settings:"ଭାଷା ଓ ପ୍ରବେଶ",open:"CareBodha ଖୋଲନ୍ତୁ",how:"ଏହା କିପରି କାମ କରେ",welcome:"CareBodhaକୁ ସ୍ୱାଗତ",hero:"ଆପଣଙ୍କ ଯତ୍ନ ବୁଝନ୍ତୁ",clarity:"ସ୍ପଷ୍ଟତା ସହିତ।",description:"ଆପଣଙ୍କ ଡାକ୍ତରଙ୍କ ନିର୍ଦ୍ଦେଶ ଆପଣଙ୍କ ଭାଷାରେ ବୁଝାଯାଏ। ଆପଣ କ’ଣ ବୁଝିଲେ କୁହନ୍ତୁ ଏବଂ ଅସ୍ପଷ୍ଟ ଅଂଶରେ ସହାୟତା ପାଆନ୍ତୁ।"},
 te:{language:"భాష",menu:"మెనూ",close:"మూసివేయండి",signin:"సైన్ ఇన్",register:"ఖాతా సృష్టించండి",email:"ఈమెయిల్ చిరునామా",password:"CareBodha పాస్‌వర్డ్",name:"పూర్తి పేరు",overview:"సారాంశం",plan:"నా సంరక్షణ ప్రణాళిక",teachback:"మీ మాటల్లో చెప్పండి",appointments:"తదుపరి సందర్శనలు",family:"కుటుంబ సహాయం",questions:"వివరణ అభ్యర్థనలు",notifications:"నోటిఫికేషన్లు",settings:"భాష మరియు యాక్సెస్",open:"CareBodha తెరవండి",how:"ఇది ఎలా పనిచేస్తుంది",welcome:"CareBodhaకు స్వాగతం",hero:"మీ సంరక్షణను అర్థం చేసుకోండి",clarity:"స్పష్టతతో.",description:"మీ వైద్యుని సూచనలు మీ భాషలో వివరించబడతాయి. మీకు అర్థమైనది చెప్పండి మరియు స్పష్టత అవసరమైన భాగాల్లో సహాయం పొందండి."},
 pa:{language:"ਭਾਸ਼ਾ",menu:"ਮੀਨੂ",close:"ਬੰਦ ਕਰੋ",signin:"ਸਾਈਨ ਇਨ",register:"ਖਾਤਾ ਬਣਾਓ",email:"ਈਮੇਲ ਪਤਾ",password:"CareBodha ਪਾਸਵਰਡ",name:"ਪੂਰਾ ਨਾਮ",overview:"ਸਾਰ",plan:"ਮੇਰੀ ਦੇਖਭਾਲ ਯੋਜਨਾ",teachback:"ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ",appointments:"ਅਗਲੀ ਮੁਲਾਕਾਤ",family:"ਪਰਿਵਾਰ ਦੀ ਮਦਦ",questions:"ਸਪਸ਼ਟੀਕਰਨ ਦੀ ਬੇਨਤੀ",notifications:"ਸੂਚਨਾਵਾਂ",settings:"ਭਾਸ਼ਾ ਅਤੇ ਪਹੁੰਚ",open:"CareBodha ਖੋਲ੍ਹੋ",how:"ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",welcome:"CareBodha ਵਿੱਚ ਸੁਆਗਤ ਹੈ",hero:"ਆਪਣੀ ਦੇਖਭਾਲ ਸਮਝੋ",clarity:"ਸਪਸ਼ਟਤਾ ਨਾਲ।",description:"ਤੁਹਾਡੇ ਡਾਕਟਰ ਦੀਆਂ ਹਦਾਇਤਾਂ ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮਝਾਈਆਂ ਜਾਂਦੀਆਂ ਹਨ। ਜੋ ਸਮਝਿਆ ਉਹ ਦੱਸੋ ਅਤੇ ਅਸਪਸ਼ਟ ਹਿੱਸਿਆਂ ਲਈ ਮਦਦ ਲਵੋ।"},
 ta:{language:"மொழி",menu:"மெனு",close:"மூடவும்",signin:"உள்நுழைக",register:"கணக்கை உருவாக்கவும்",email:"மின்னஞ்சல் முகவரி",password:"CareBodha கடவுச்சொல்",name:"முழுப் பெயர்",overview:"கண்ணோட்டம்",plan:"எனது பராமரிப்புத் திட்டம்",teachback:"உங்கள் சொற்களில் கூறவும்",appointments:"அடுத்த சந்திப்புகள்",family:"குடும்ப உதவி",questions:"விளக்கக் கோரிக்கைகள்",notifications:"அறிவிப்புகள்",settings:"மொழி மற்றும் அணுகல்",open:"CareBodha திறக்கவும்",how:"இது எப்படி வேலை செய்கிறது",welcome:"CareBodha-விற்கு வரவேற்கிறோம்",hero:"உங்கள் பராமரிப்பைப் புரிந்துகொள்ளுங்கள்",clarity:"தெளிவுடன்.",description:"உங்கள் மருத்துவரின் அறிவுறுத்தல்கள் உங்கள் மொழியில் விளக்கப்படுகின்றன. நீங்கள் புரிந்துகொண்டதைப் பகிர்ந்து, தெளிவு தேவைப்படும் பகுதிகளில் உதவி பெறுங்கள்."}
};
