import {test,expect,request} from "@playwright/test";
import {PrismaClient} from "@prisma/client";
test("approved text audio, automatic teach-back, reminder scheduling and all workspace screens",async({page})=>{
 test.skip(process.env.APP_MODE!=="normal","Use the isolated normal database.");
 if(new URL(process.env.DATABASE_URL!).pathname!=="/carebodha_normal_test")throw Error("Isolated database required.");
 const db=new PrismaClient(),origin=process.env.BETTER_AUTH_URL!,email=`workspace-${Date.now()}@example.test`,password="Workspace-check-2026!";
 const api=await request.newContext({baseURL:origin,extraHTTPHeaders:{Origin:origin}});
 try{
  expect((await api.post("/api/auth/sign-up/email",{data:{email,password,name:"Care Workspace Patient"}})).status()).toBe(200);
  const w=(await (await api.get("/api/v1/workspace")).json()).data;
  const plan=await db.carePlan.create({data:{patientId:w.selectedPatientId,dataMode:"normal",title:"Fictional medicine routine",versions:{create:{number:1,status:"APPROVED",approvedAt:new Date(),method:"test fixture",instructions:{create:{kind:"MEDICATION",title:"Fictional tablet",medicationName:"Fictional tablet",dose:"1",unit:"tablet",frequency:"twice daily",sourcePassage:"Take 1 tablet twice daily.",reviewState:"APPROVED",explanations:{create:{language:"en",status:"APPROVED",text:"Take 1 tablet twice daily.",sourceFields:["dose","unit","frequency"],method:"test fixture"}}}}}}},include:{versions:{include:{instructions:true}}}});
  const version=plan.versions[0],instruction=version.instructions[0];await db.carePlan.update({where:{id:plan.id},data:{approvedVersionId:version.id}});
  const answer=(transcript:string)=>api.post("/api/v1/teachback",{data:{instructionId:instruction.id,transcript,inputMode:"TEXT",transcriptConfirmed:true,personType:"PATIENT"}});
  expect((await (await answer("I will take 1 tablet twice daily.")).json()).data.status).toBe("MATCH");
  expect((await (await answer("I will take 2 tablets once daily.")).json()).data.status).toBe("MISMATCH");
  expect((await api.patch("/api/v1/phone-preferences",{data:{smsReminders:true}})).status()).toBe(422);
  const times=[1,2,3].map(n=>new Date(Date.now()+n*86400000).toISOString());const response=await api.post("/api/v1/reminders/batch",{data:{instructionIds:[instruction.id],scheduledAt:times,timezone:"Asia/Kolkata"}});expect(response.status()).toBe(200);expect((await response.json()).data.reminders).toHaveLength(3);
  await page.goto("/signin");await page.getByLabel("Email or username",{exact:true}).fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/\/app$/);
  for(const section of ["overview","plan","teachback","appointments","family","questions","notifications","settings"]){await page.goto(`/app/${section}`);await expect(page.locator(".app-content .page-heading h1")).toBeVisible();await page.screenshot({path:`.local-browser-media/solus-${section}-desktop.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
  await page.goto("/app/plan");expect(await page.getByText("View original source",{exact:true}).count()).toBe(0);await page.getByRole("combobox",{name:"Language / भाषा"}).selectOption("bn");await expect(page.locator(".pending-indicator")).toHaveCount(0);
  await page.evaluate(()=>{Object.assign(window,{SpeechSynthesisUtterance:class {lang="";voice=null;rate=1;constructor(public text:string){}}});Object.assign(window.speechSynthesis,{cancel(){},getVoices(){return [{lang:"en-IN",name:"English"}]},speak(u:{text:string;lang:string}){Object.assign(window,{__audio:{text:u.text,lang:u.lang}})}});});
  await page.locator(".instruction-card .card-buttons button").first().click();await expect.poll(()=>page.evaluate(()=>(window as unknown as {__audio:{text:string;lang:string}}).__audio)).toMatchObject({text:"Take 1 tablet twice daily.",lang:"en-IN"});
  await page.setViewportSize({width:390,height:844});for(const section of ["overview","plan","teachback","appointments","family","questions","notifications","settings"]){await page.goto(`/app/${section}`);await expect(page.locator(".app-content .page-heading h1")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`.local-browser-media/solus-${section}-mobile.png`,fullPage:true});}
  await page.getByRole("combobox",{name:"Language / भाषा"}).selectOption("en");await expect(page.locator(".pending-indicator")).toHaveCount(0);await page.goto("/expert/signin");await expect(page.locator(".auth-portrait.doctor")).toBeVisible();await page.screenshot({path:".local-browser-media/solus-expert-signin-mobile.png",fullPage:true});await page.goto("/signin");await expect(page.locator(".auth-portrait.patient")).toBeVisible();await page.screenshot({path:".local-browser-media/solus-patient-signin-mobile.png",fullPage:true});await page.getByRole("button",{name:"Phone OTP",exact:true}).click();await page.getByLabel("Registered phone number",{exact:true}).fill("+919876543210");await page.getByRole("button",{name:"Send sign-in code",exact:true}).click();await expect(page.locator(".auth-card [role=alert]")).toContainText("Phone OTP is temporarily unavailable");
 }finally{await api.dispose();await db.$disconnect();}
});
