import {test,expect} from "@playwright/test";
test("medical gallery selection and dragging work, with readable static equipment on reduced motion",async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.setViewportSize({width:1440,height:960});await page.goto('/');
 await page.evaluate(()=>{const el=document.querySelector('.gallery-stage')!;window.scrollTo({top:scrollY+el.getBoundingClientRect().top,behavior:'instant'});});
 await expect(page.locator('.equipment-label')).toHaveText('Stethoscope');await expect(page.locator('.chapter-scene-gallery.is-ready canvas')).toBeVisible();
 await page.getByRole('button',{name:/03.*CLARIFY/}).click();await expect(page.locator('.equipment-label')).toHaveText('IV stand');
 await page.mouse.move(900,350);await page.mouse.down();await page.mouse.move(1380,350,{steps:24});await page.mouse.up();await expect(page.locator('.equipment-label')).toHaveText('Blood-pressure monitor');
 await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.chapter-scene-gallery canvas')).toHaveCount(0);
 await page.getByRole('button',{name:/01.*UNDERSTAND/}).click();await expect(page.locator('.equipment-label')).toHaveText('Stethoscope');await expect(page.locator('.equipment-stethoscope').first()).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.querySelector('#family')!.scrollIntoView({behavior:'instant'}));
 await expect(page.getByRole('link',{name:'Explore family assistance',exact:true})).toBeVisible();
 const familyLink=await page.getByRole('link',{name:'Explore family assistance',exact:true}).boundingBox();expect(familyLink!.y+familyLink!.height).toBeLessThanOrEqual(844);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test("second-chapter text, remaining immersive scenes, readable menu and custom cursor",async({page})=>{
 await page.setViewportSize({width:1440,height:960});await page.goto('/');await expect(page.locator('.landing-experience')).toHaveAttribute('data-intro','done');
 await page.mouse.move(500,350);await expect(page.locator('html')).toHaveClass(/matter-cursor-active/);await expect.poll(()=>page.locator('.matter-cursor-ring').evaluate(el=>getComputedStyle(el).opacity)).toBe('1');
 await page.mouse.wheel(0,2700);await expect(page.locator('.hero-stage')).toHaveAttribute('data-chapter','matter');await expect.poll(()=>page.locator('.matter-type-one').evaluate(el=>Number(getComputedStyle(el).opacity))).toBeGreaterThan(.9);const one=await page.locator('.matter-type-one').evaluate(el=>getComputedStyle(el).translate);await page.mouse.wheel(0,250);await expect.poll(()=>page.locator('.matter-type-one').evaluate(el=>getComputedStyle(el).translate)).not.toBe(one);await page.screenshot({path:'docs/screenshots/refined-matter.png'});
 await page.getByRole('button',{name:'MENU',exact:true}).click();await expect(page.getByRole('link',{name:'How it works',exact:true})).toBeFocused();await page.locator('.landing-menu').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished));});await page.screenshot({path:'docs/screenshots/refined-menu-desktop.png'});await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'CLOSE',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'MENU',exact:true})).toBeFocused();await expect(page.getByRole('navigation',{name:'Main navigation'})).toHaveCount(0);
 await page.evaluate(()=>document.querySelector('.gallery-stage')!.scrollIntoView({behavior:'instant',block:'start'}));await expect(page.locator('.chapter-scene-gallery.is-ready canvas')).toBeVisible();await page.mouse.wheel(0,620);await expect(page.locator('.gallery-stage')).toHaveAttribute('data-active','1');await expect(page.getByRole('heading',{name:'EXPLAIN BACK',exact:true}).first()).toBeVisible();await page.locator('.gallery-caption').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished));});await page.screenshot({path:'docs/screenshots/refined-gallery.png'});
 await page.evaluate(()=>{const el=document.querySelector('.typography-stage')!;window.scrollTo({top:scrollY+el.getBoundingClientRect().top+150,behavior:'instant'});});await expect(page.locator('.typography-stage')).toHaveAttribute('data-word','0');await expect.poll(()=>page.locator('.depth-word').first().evaluate(el=>Number(getComputedStyle(el).opacity))).toBeGreaterThan(.8);expect(await page.locator('.depth-char').first().evaluate(el=>getComputedStyle(el).transform)).not.toBe('none');await page.screenshot({path:'docs/screenshots/refined-typography.png'});
 await page.locator('#family').scrollIntoViewIfNeeded();await expect(page.locator('.chapter-scene-physics.is-ready canvas')).toBeVisible();await page.locator('#family h2').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished));});await page.screenshot({path:'docs/screenshots/refined-family.png'});
 await page.getByRole('link',{name:'SCROLL DOWN'}).click();await expect(page.locator('.closing-stage')).toHaveAttribute('data-transition','outro');await expect(page.locator('.chapter-scene-rings.is-ready canvas')).toBeVisible();await expect(page.locator('.final-cta h2')).toHaveClass(/is-revealed/);await page.locator('.final-cta h2').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished));});await page.screenshot({path:'docs/screenshots/refined-final.png'});
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'MENU',exact:true}).click();await page.locator('.landing-menu').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished));});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const link of await page.locator('.menu-links a').all()){const b=await link.boundingBox();expect(b!.x+b!.width).toBeLessThanOrEqual(390);}await page.screenshot({path:'docs/screenshots/refined-menu-mobile.png'});await page.getByRole('link',{name:'Teach-back',exact:true}).click();await page.getByRole('button',{name:'Check my understanding'}).click();await expect(page.getByText('Mismatch detected — frequency')).toBeVisible();
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await expect(page.locator('.chrome-scene canvas')).toHaveCount(0);expect(await page.locator('.typography-stage').evaluate(el=>el.getBoundingClientRect().height)).toBeLessThan(1100);await expect(page.locator('html')).not.toHaveClass(/matter-cursor-active/);
});
