import {test,expect,request} from "@playwright/test";
import {PrismaClient} from "@prisma/client";
import {hashPassword} from "better-auth/crypto";
test("normal accounts, private source, seven languages, clinician approval and human teach-back review",async({page})=>{
 test.skip(process.env.APP_MODE!=="normal","Run scripts/verify-normal.mjs against the isolated normal test database.");
 const db=new PrismaClient();const origin=process.env.BETTER_AUTH_URL!;const stamp=Date.now();const password="Acceptance-password-2026!";
 const patient=await request.newContext({baseURL:origin,extraHTTPHeaders:{Origin:origin}}),clinician=await request.newContext({baseURL:origin,extraHTTPHeaders:{Origin:origin}});
 try{
  await page.goto("/register");await page.getByLabel("Full name",{exact:true}).fill("Verification Patient");await page.getByLabel("Email address",{exact:true}).fill(`normal-${stamp}@example.test`);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByRole("button",{name:"Create account",exact:true}).click();await expect(page).toHaveURL(/\/app$/);await expect(page.getByRole("combobox",{name:"Language / भाषा"})).toBeVisible();
  await patient.post('/api/auth/sign-in/email',{data:{email:`normal-${stamp}@example.test`,password}});const workspace=(await (await patient.get('/api/v1/workspace')).json()).data;expect(workspace.mode).toBe('normal');expect(workspace.plans).toHaveLength(0);const patientId=workspace.selectedPatientId;
  const doctor=await db.user.create({data:{name:'Verification Clinician',email:`doctor-${stamp}@example.test`,role:'CLINICIAN',dataMode:'normal',emailVerified:true}});await db.account.create({data:{userId:doctor.id,accountId:doctor.id,providerId:"credential",password:await hashPassword(password)}});await db.clinicianPatientAssignment.create({data:{clinicianId:doctor.id,patientId}});expect((await clinician.post('/api/auth/sign-in/email',{data:{email:doctor.email,password}})).status()).toBe(200);
  const source='Bring your discharge document to the appointment.';const upload=await clinician.post('/api/v1/documents',{multipart:{patientId,text:source}});expect(upload.status()).toBe(200);const documentId=(await upload.json()).data.id;await expect.poll(async()=>(await db.document.findUniqueOrThrow({where:{id:documentId}})).status,{timeout:20000}).toBe('READY');expect((await patient.get(`/api/v1/documents/${documentId}`)).status()).toBe(403);
  let w=(await (await clinician.get(`/api/v1/workspace?patientId=${patientId}`)).json()).data;const version=w.plans[0].versions[0],instruction=version.instructions[0];const fields=['kind','title','medicationName','dose','unit','route','frequency','timing','duration','followUpAt','sourcePassage','sourceLocation','sourceUnclear'];expect((await clinician.patch(`/api/v1/instructions/${instruction.id}`,{data:{instruction:Object.fromEntries(fields.map(f=>[f,instruction[f]])),reviewed:true}})).status()).toBe(200);expect((await clinician.post(`/api/v1/versions/${version.id}/generate`)).status()).toBe(200);
  w=(await (await clinician.get(`/api/v1/workspace?patientId=${patientId}`)).json()).data;const explanations=w.plans[0].versions[0].instructions[0].explanations;expect(explanations).toHaveLength(7);const reviewed:Record<string,string>={en:source,hi:'मुलाकात में अपना डिस्चार्ज दस्तावेज़ साथ लाएँ।',bn:'সাক্ষাতে আপনার ডিসচার্জের নথি সঙ্গে আনুন।'};for(const e of explanations)if(reviewed[e.language])expect((await clinician.patch(`/api/v1/explanations/${e.id}`,{data:{text:reviewed[e.language],reviewed:true}})).status()).toBe(200);expect((await clinician.post(`/api/v1/versions/${version.id}/approve`)).status()).toBe(200);
  const published=(await (await patient.get('/api/v1/workspace')).json()).data.plans[0].versions[0].instructions[0];expect(published.explanations.map((e:{language:string})=>e.language).sort()).toEqual(['bn','en','hi']);
  for(const code of ['en','hi','bn','or','te','pa','ta'])expect((await patient.patch('/api/v1/settings',{data:{language:code,timezone:'Asia/Kolkata',largeText:false}})).status()).toBe(200);
  await page.goto('/app/plan');await expect(page.getByRole('combobox',{name:'Language / भाषा'})).toBeVisible();await page.getByRole('combobox',{name:'Language / भाषा'}).selectOption('bn');await expect(page.getByText(reviewed.bn,{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('combobox',{name:'Language / भाषा'})).toHaveValue('bn');await page.screenshot({path:'docs/screenshots/normal-bengali-plan.png',fullPage:true});await page.getByRole('combobox',{name:'Language / भाषा'}).selectOption('or');await expect(page.getByText(/A clinician-approved Odia translation is not available/)).toBeVisible();await expect(page.getByText(source,{exact:true}).first()).toBeVisible();
  const attempt=await patient.post('/api/v1/teachback',{data:{instructionId:instruction.id,transcript:'আমি আমার নথি নিয়ে আসব।',inputMode:'TEXT',transcriptConfirmed:true,personType:'PATIENT'}});expect(attempt.status()).toBe(200);expect((await attempt.json()).data.status).toBe('NEEDS_CLINICIAN_REVIEW');const review=(await (await clinician.get(`/api/v1/workspace?patientId=${patientId}`)).json()).data;expect(review.requests).toHaveLength(1);expect((await clinician.patch(`/api/v1/clarifications/${review.requests[0].id}`,{data:{response:'We received your answer. Please read the approved instruction with your care team.'}})).status()).toBe(200);
  const fresh=await request.newContext({baseURL:origin,extraHTTPHeaders:{Origin:origin}});expect((await fresh.post('/api/auth/sign-in/email',{data:{email:`normal-${stamp}@example.test`,password}})).status()).toBe(200);expect((await (await fresh.get('/api/v1/workspace')).json()).data.attempts).toHaveLength(1);await fresh.dispose();
 }finally{await patient.dispose();await clinician.dispose();await db.$disconnect();}
});
