import {afterEach,describe,expect,it,vi} from "vitest";
vi.mock("../src/lib/db",()=>({db:{reminder:{findUnique:vi.fn(),updateMany:vi.fn(),update:vi.fn()}}}));
import {db} from "../src/lib/db";
import {sendSms,validPhone} from "../src/lib/sms";
import {deliverReminderSms} from "../src/lib/reminder-sms";
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();vi.clearAllMocks();});
function configure(){vi.stubEnv("SMS_PROVIDER","twilio");vi.stubEnv("TWILIO_ACCOUNT_SID",`AC${"a".repeat(32)}`);vi.stubEnv("TWILIO_AUTH_TOKEN","test-secret");vi.stubEnv("TWILIO_MESSAGING_SERVICE_SID","test-service");}
describe("phone messaging",()=>{
 it("rejects missing service configuration without sending any request",async()=>{vi.stubEnv("SMS_PROVIDER","none");const fetcher=vi.fn();vi.stubGlobal("fetch",fetcher);await expect(sendSms("+919876543210","test")).rejects.toThrow("not configured");expect(fetcher).not.toHaveBeenCalled();expect(validPhone("9876543210")).toBe(false);expect(validPhone("+919876543210")).toBe(true);});
 it("does not expose provider errors or credentials",async()=>{configure();vi.stubGlobal("fetch",vi.fn(async()=>new Response("sensitive provider details",{status:401})));await expect(sendSms("+919876543210","fictional code")).rejects.toThrow("could not send");});
 it("sends a medicine-specific reminder only once after consent and current-plan checks",async()=>{configure();const fetcher=vi.fn(async()=>new Response(JSON.stringify({sid:"SM-fixture"})));vi.stubGlobal("fetch",fetcher);const fixture={id:"r",smsRequested:true,smsStatus:"PENDING",status:"NOTIFIED",instruction:{versionId:"v",medicationName:"Fictional training tablet",version:{plan:{approvedVersionId:"v",patient:{smsReminders:true,user:{phoneNumberVerified:true,phoneNumber:"+919876543210"}}}}}};vi.mocked(db.reminder.findUnique).mockResolvedValue(fixture as never);vi.mocked(db.reminder.updateMany).mockResolvedValueOnce({count:1}).mockResolvedValueOnce({count:0});await deliverReminderSms("r");await deliverReminderSms("r");expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0]).toBeDefined();expect(db.reminder.update).toHaveBeenCalledWith({where:{id:"r"},data:{smsStatus:"SENT",smsProviderId:"SM-fixture"}});});
 it("never sends SMS for superseded instructions",async()=>{configure();const fetcher=vi.fn();vi.stubGlobal("fetch",fetcher);vi.mocked(db.reminder.findUnique).mockResolvedValue({smsRequested:true,smsStatus:"PENDING",status:"NOTIFIED",instruction:{versionId:"old",version:{plan:{approvedVersionId:"new",patient:{smsReminders:true,user:{phoneNumberVerified:true,phoneNumber:"+919876543210"}}}}}} as never);await deliverReminderSms("r");expect(fetcher).not.toHaveBeenCalled();expect(db.reminder.updateMany).toHaveBeenCalledWith({where:{id:"r",smsStatus:"PENDING"},data:{smsStatus:"SKIPPED"}});});
});
