"use client";
import {UiText,useUi} from "./ui-text";
import {useState} from "react";
import Link from "next/link";
import {Plus,Users,Upload,ClipboardList} from "lucide-react";

type Patient={id:string;user:{name:string;email:string;username?:string|null}};
export function ExpertPatients({patients,selectedId,assign,select,pending}:{patients:Patient[];selectedId:string|null;assign:(identifier:string)=>Promise<{patientId:string;message:string}>;select:(id:string)=>void;pending:boolean}) { const ui=useUi();
  const [identifier,setIdentifier]=useState("");const [success,setSuccess]=useState("");
  async function submit(e:React.FormEvent) {
    e.preventDefault();setSuccess("");
    try{const result=await assign(identifier.trim());setSuccess(result.message);setIdentifier("");select(result.patientId);}catch{/* The workspace displays the server's actionable error. */}
  }
  return <div className="expert-patients"><section className="panel connection-panel"><div className="panel-heading"><div><span className="micro-label"><UiText>{"01 — CONNECT YOUR PATIENT"}</UiText></span><h2><UiText>{"Care starts with a connection."}</UiText></h2></div><Plus size={26}/></div><p><UiText>{"Use the email address or username from the patient’s registered CareBodha account. They are connected immediately; no patient acceptance is required."}</UiText></p><form onSubmit={submit}><label><UiText>{"Patient email or username"}</UiText><input required maxLength={254} autoComplete="off" placeholder={ui("patient@gmail.com or asha_sharma")} value={identifier} onChange={e=>{setIdentifier(e.target.value);setSuccess("");}}/></label><button className="button primary" disabled={pending || !identifier.trim()}><Plus size={18}/><UiText>{"Connect patient"}</UiText></button></form>{success && <p className="connection-success" role="status"><UiText>{success}</UiText></p>}<p className="field-help"><UiText>{"Upload their source instructions next. A care plan becomes available to the patient only after your review and approval."}</UiText></p></section><section className="panel"><div className="panel-heading"><h2><UiText>{"Connected patients"}</UiText></h2><Users size={22}/></div>{!patients.length?<p><UiText>{"No patients connected yet. Add a registered patient above to begin."}</UiText></p>:<div className="connected-patients">{patients.map(patient=><article className="connected-patient" key={patient.id}><div><h3>{patient.user.name}</h3><p>{patient.user.email}{patient.user.username && <><br/>@{patient.user.username}</>}</p></div><div className="card-buttons"><button className="button secondary" aria-pressed={patient.id===selectedId} onClick={()=>select(patient.id)}><UiText>{patient.id===selectedId?"Selected":"Select patient"}</UiText></button><Link className="button primary" href={`/app/upload?patientId=${encodeURIComponent(patient.id)}`}><Upload size={17}/><UiText>{"Upload care"}</UiText></Link><Link className="button secondary" href={`/app/review?patientId=${encodeURIComponent(patient.id)}`}><ClipboardList size={17}/><UiText>{"Review care"}</UiText></Link></div></article>)}</div>}</section></div>;
}
