"use client";
import {useEffect,useRef} from "react";
export function MatterCursor(){const dot=useRef<HTMLDivElement>(null),ring=useRef<HTMLDivElement>(null);
 useEffect(()=>{const d=dot.current,r=ring.current;if(!d || !r)return;const fine=matchMedia("(hover:hover) and (pointer:fine)"),reduce=matchMedia("(prefers-reduced-motion: reduce)");let raf=0,x=0,y=0,rx=0,ry=0,active=false,previous=performance.now();
 const closing=document.querySelector<HTMLElement>(".closing-stage");let closingPhase="";
 const hover=(element:Element|null)=>{const target=element?.closest("a,button,summary"),drag=element?.closest(".gallery-drag-zone"),finale=element?.closest("#family") && closing?.dataset.transition==="support";r.classList.toggle("is-link",!!target);r.classList.toggle("is-scene",!target && !!drag);r.classList.toggle("is-finale",!!finale);d.classList.toggle("is-finale",!!finale);const label=r.querySelector("span");if(label)label.textContent=!target && drag?"DRAG":"";};
 const scroll=()=>{if(active)hover(document.elementFromPoint(x,y));};
 const move=(e:PointerEvent)=>{if(e.pointerType!=="mouse" || !fine.matches || reduce.matches)return;const inside=(e.target as Element)?.closest(".landing-experience"),editable=(e.target as Element)?.closest("input,textarea,select");active=!!inside && !editable;document.documentElement.classList.toggle("matter-cursor-active",active);if(!active)return;x=e.clientX;y=e.clientY;if(d.style.opacity!=="1"){rx=x;ry=y;}d.style.opacity=r.style.opacity="1";hover(e.target as Element);};
 const hide=()=>{active=false;document.documentElement.classList.remove("matter-cursor-active");d.style.opacity=r.style.opacity="0";};
 const tick=(now:number)=>{raf=requestAnimationFrame(tick);const dt=Math.min(.05,(now-previous)/1000);previous=now;if(!active || document.hidden){d.style.opacity=r.style.opacity="0";return;}if(closingPhase!==closing?.dataset.transition){closingPhase=closing?.dataset.transition || "";hover(document.elementFromPoint(x,y));}rx+=(x-rx)*(1-Math.exp(-12*dt));ry+=(y-ry)*(1-Math.exp(-12*dt));d.style.transform=`translate3d(${x}px,${y}px,0)`;r.style.transform=`translate3d(${rx}px,${ry}px,0)`;};
 window.addEventListener("scroll",scroll,{passive:true});document.addEventListener("pointermove",move,{passive:true});document.addEventListener("pointerleave",hide);window.addEventListener("blur",hide);fine.addEventListener("change",hide);reduce.addEventListener("change",hide);raf=requestAnimationFrame(tick);
 return()=>{cancelAnimationFrame(raf);hide();window.removeEventListener("scroll",scroll);document.removeEventListener("pointermove",move);document.removeEventListener("pointerleave",hide);window.removeEventListener("blur",hide);fine.removeEventListener("change",hide);reduce.removeEventListener("change",hide);};},[]);
 return <><div ref={dot} className="matter-cursor-dot" aria-hidden="true"/><div ref={ring} className="matter-cursor-ring" aria-hidden="true"><span/></div></>;
}
