"use client";
import {useState} from "react";
import {UiText} from "./ui-text";
export function PasswordRecovery({onClose}:{onClose:()=>void}) {
 const [phone,setPhone]=useState("+91"),[code,setCode]=useState(""),[password,setPassword]=useState(""),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[done,setDone]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{
  const response=await fetch(`/api/auth/phone-number/${sent?"reset-password":"request-password-reset"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phoneNumber:phone,...(sent?{otp:code,newPassword:password}:{})})});const data=await response.json();if(!response.ok)throw Error(data.message||"Password recovery failed. Please try again.");if(sent){setDone(true);setMessage("Password updated. Sign in with your new CareBodha password.");}else{setSent(true);setMessage("Code sent. It expires in 5 minutes. Never share it.");}
 }catch(error){setMessage(error instanceof Error?error.message:"Please try again.");}finally{setBusy(false);}}
 return <form onSubmit={submit}><h3><UiText>Reset your CareBodha password</UiText></h3><p><UiText>We send a verification code only to your registered, verified phone number.</UiText></p>{!done&&<><label><UiText>Registered phone number</UiText><input type="tel" autoComplete="tel" required pattern="\+[1-9][0-9]{7,14}" value={phone} disabled={sent||busy} onChange={e=>setPhone(e.target.value.replace(/\s/g,""))}/></label>{sent&&<><label><UiText>Verification code</UiText><input inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/></label><label><UiText>New CareBodha password</UiText><input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label></>}<button className="button primary full" disabled={busy}><UiText>{busy?"Please wait…":sent?"Verify and reset password":"Send verification code"}</UiText></button></>}{message&&<p role="status"><UiText>{message}</UiText></p>}<button type="button" className="text-link" onClick={onClose}><UiText>Back to sign-in</UiText></button></form>;
}
