"use client";
import {useState} from "react";
import {authClient} from "@/lib/auth-client";
import {Phone,ShieldCheck} from "lucide-react";
import {UiText} from "./ui-text";
export function PhoneAccess({user,smsEnabled,available,smsAvailable,refresh}:{user:{phoneNumber?:string|null;phoneNumberVerified?:boolean};smsEnabled:boolean;available:boolean;smsAvailable:boolean;refresh:()=>Promise<unknown>}){
 const [phone,setPhone]=useState(user.phoneNumber||"+91");const [code,setCode]=useState("");const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [consent,setConsent]=useState(smsEnabled);
 async function perform(task:()=>Promise<unknown>){setBusy(true);setMessage("");try{await task();}catch(e){setMessage(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
 return <section className="panel phone-access"><div className="panel-heading"><h2><UiText>{"Your phone, connected"}</UiText></h2><Phone size={22}/></div><p><UiText>{"Verify your own number for phone OTP sign-in and medicine reminders."}</UiText></p>{user.phoneNumberVerified&&<p className="green"><ShieldCheck size={16}/> {user.phoneNumber} <UiText>{"Verified"}</UiText></p>}
 {!available&&<p className="alert amber" role="status"><UiText>{"Phone verification is not connected yet. In-app reminders remain available."}</UiText></p>}<form onSubmit={e=>{e.preventDefault();void perform(async()=>{if(sent){const result=await authClient.phoneNumber.verify({phoneNumber:phone,code,updatePhoneNumber:true,disableSession:true});if(result.error)throw new Error(result.error.message||"That code could not be verified.");setSent(false);setCode("");await refresh();setMessage("Phone number verified.");}else{const result=await authClient.phoneNumber.sendOtp({phoneNumber:phone},{headers:{"x-carebodha-phone-purpose":"update"}});if(result.error)throw new Error(result.error.message||"SMS could not be sent.");setSent(true);setMessage("A verification code was sent to your phone.");}});}}><label><UiText>{"Phone number with country code"}</UiText><input type="tel" autoComplete="tel" pattern="\+[1-9][0-9]{7,14}" required value={phone} disabled={sent||busy} onChange={e=>setPhone(e.target.value)}/></label>{sent&&<label><UiText>{"6-digit verification code"}</UiText><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label>}<button className="button secondary" disabled={busy||!available}><UiText>{sent?"Verify phone":"Send verification code"}</UiText></button>{sent&&<button className="text-link" type="button" onClick={()=>{setSent(false);setCode("");}}><UiText>{"Change number"}</UiText></button>}</form>
 {!smsAvailable&&<p className="field-help"><UiText>{"SMS medicine reminders are unavailable on this verification-only service. In-app reminders still work."}</UiText></p>}<label className="checkbox-row"><input type="checkbox" checked={consent} disabled={!user.phoneNumberVerified||busy||!smsAvailable} onChange={e=>setConsent(e.target.checked)}/><UiText>{"Send medicine reminder SMS to my verified phone. Messages may include the medicine name."}</UiText></label><button className="button primary" disabled={busy||!user.phoneNumberVerified||!smsAvailable} onClick={()=>void perform(async()=>{const response=await fetch("/api/v1/phone-preferences",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({smsReminders:consent})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||"Could not save phone preferences.");await refresh();setMessage("Phone preferences saved.");})}><UiText>{"Save phone preferences"}</UiText></button>{message&&<p role="status" className="field-help"><UiText>{message}</UiText></p>}</section>;
}
