"use client";
import {useState} from "react";
import {authClient} from "@/lib/auth-client";
import {UiText} from "./ui-text";
export function PhoneSignin(){
 const [phone,setPhone]=useState("+91"),[code,setCode]=useState(""),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{if(sent){const result=await authClient.phoneNumber.verify({phoneNumber:phone,code});if(result.error)throw new Error(result.error.message||"Check your code and try again.");window.location.href="/app";}else{const result=await authClient.phoneNumber.sendOtp({phoneNumber:phone});if(result.error)throw new Error(result.error.message||"Phone OTP is unavailable. Use your CareBodha password.");setSent(true);}}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}}>
 <p className="signin-note"><UiText>{"Use the phone number you verified in Language & access. New patients can register with email and password first."}</UiText></p><label><UiText>{"Registered phone number"}</UiText><input type="tel" autoComplete="tel" pattern="\+[1-9][0-9]{7,14}" placeholder="+91 9876543210" required disabled={sent||busy} value={phone} onChange={e=>setPhone(e.target.value.replace(/\s/g,""))}/></label>{sent&&<><label><UiText>{"6-digit sign-in code"}</UiText><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label><p className="field-help"><UiText>{"Code expires in 5 minutes."}</UiText></p></>}{error&&<p role="alert" className="alert red"><UiText>{error}</UiText></p>}<button className="button primary full" disabled={busy}><UiText>{busy?"Please wait…":sent?"Verify and sign in":"Send sign-in code"}</UiText></button>{sent&&<button type="button" className="text-link" onClick={()=>{setSent(false);setCode("");}}><UiText>{"Use a different number"}</UiText></button>}</form>;
}
